#!/bin/bash

array=(`ls`)

echo 'practice: shell command and array'
echo "list all directories and files in current directory: ${array[@]}"
echo "total number of files and directories: ${#array[@]}"
echo "the first element in this list: ${array[0]}"

for dir in ${array[@]}
do
	echo $dir
done
