#!/bin/bash

if [ $# -ne 1 ]
then
	echo 'usage: mysolution [course-number]'
	exit
fi

array_id=(`cat courses.txt | grep $1 | cut -f1`)

if [ ${#array_id[@]} -eq 0 ]
then
	echo "course number $1 not found"
fi

for id in ${array_id[@]}
do
	echo `cat emails.txt | grep $id | cut -f2`
done
