#!/bin/bash

pass_grades_array1=(`cat 60-212 | grep '\([56789][0-9]\)\|100' | cut -f1`)
pass_grades_array2=(`cat 60-256 | grep '\([56789][0-9]\)\|100' | cut -f1`)

#echo ${pass_grades_array1[@]}
#echo ${pass_grades_array2[@]}

for student1 in ${pass_grades_array1[@]}
do
	for student2 in ${pass_grades_array2[@]}
	do
		if [ $student1 -eq $student2 ]
		then
			echo $student1
		fi
	done
done
